import Vue from "vue";
import {
  Icon,
  Tab,
  Tabs,
  List,
  Cell,
  Button,
  Popup,
  Field,
  Dialog,
  Toast,
  Swipe,
  SwipeItem,
  Area,
  NavBar,
  CellGroup,
  Image,
  Sticky,
  Tabbar,
  TabbarItem,
  Lazyload,
  CountDown,
  DropdownMenu,
  DropdownItem,
  Row,
  Col,
  Radio,
  RadioGroup,
  TreeSelect,
  Checkbox,
  CheckboxGroup,
  Sidebar,
  SidebarItem,
  AddressEdit,
  Step,
  Steps,
  ActionSheet,
  Panel,
  Switch,
  Grid,
  GridItem,
  NoticeBar,
  Uploader,
} from "vant";

Vue.use(Uploader);
Vue.use(NoticeBar);
Vue.use(Grid).use(GridItem);
Vue.use(Panel);
Vue.use(Icon);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(List);
Vue.use(Cell);
Vue.use(Button);
Vue.use(Popup);
Vue.use(Field);
Vue.use(Dialog);
Vue.use(Toast);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Area);
Vue.use(NavBar);
Vue.use(CellGroup);
Vue.use(Image);
Vue.use(Sticky);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Lazyload);
Vue.use(CountDown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Row);
Vue.use(Col);
Vue.use(RadioGroup);
Vue.use(Radio);
Vue.use(TreeSelect);
Vue.use(Checkbox).use(CheckboxGroup);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(AddressEdit);
Vue.use(Step).use(Steps);
Vue.use(ActionSheet);
Vue.use(Switch);